spring.application.name=ROUTESPHERE-GATEWAY

spring.main.allow-bean-definition-overriding=true

server.port=8080

eureka.client.service-url.defaultZone=http://rds:8761/eureka

jwt.secret=Hyshaksooekamkisgtla-kaiSMKEiEmaksiem
jwt.expiration=3600000

spring.cloud.gateway.server.webmvc.routes[0].id=vehicle-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ROUTESPHERE-VEHICLE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/vehicle/**

spring.cloud.gateway.server.webmvc.routes[1].id=driver-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ROUTESPHERE-DRIVER
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/driver/**

spring.cloud.gateway.server.webmvc.routes[2].id=customer-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ROUTESPHERE-CUSTOMER
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/customer/**

spring.cloud.gateway.server.webmvc.routes[3].id=shipment-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ROUTESPHERE-SHIPMENT
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/shipment/**

spring.cloud.gateway.server.webmvc.routes[4].id=invoice-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ROUTESPHERE-INVOICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/invoice/**

spring.cloud.gateway.server.webmvc.routes[5].id=maintenance-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ROUTESPHERE-MAINTENANCE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/maintenance/**

spring.cloud.gateway.server.webmvc.routes[6].id=trip-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ROUTESPHERE-TRIP
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/trip/**

spring.cloud.gateway.server.webmvc.routes[7].id=fuellog-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://ROUTESPHERE-FUELLOG
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/log/**

spring.cloud.gateway.server.webmvc.routes[8].id=auth-service
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ROUTESPHERE-AUTH
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/auth/**

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Vehicle Service
springdoc.swagger-ui.urls[1].url=/vehicle/v3/api-docs

springdoc.swagger-ui.urls[2].name=Driver Service
springdoc.swagger-ui.urls[2].url=/driver/v3/api-docs

springdoc.swagger-ui.urls[3].name=Customer Service
springdoc.swagger-ui.urls[3].url=/customer/v3/api-docs

springdoc.swagger-ui.urls[4].name=Shipment Service
springdoc.swagger-ui.urls[4].url=/shipment/v3/api-docs

springdoc.swagger-ui.urls[5].name=Invoice Service
springdoc.swagger-ui.urls[5].url=/invoice/v3/api-docs

springdoc.swagger-ui.urls[6].name=Trip Service
springdoc.swagger-ui.urls[6].url=/trip/v3/api-docs

springdoc.swagger-ui.urls[7].name=Maintenance Service
springdoc.swagger-ui.urls[7].url=/maintenance/v3/api-docs

springdoc.swagger-ui.urls[8].name=Fuel Log Service
springdoc.swagger-ui.urls[8].url=/log/v3/api-docs


spring.cloud.gateway.server.webmvc.routes[9].id=vehicle-docs
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://ROUTESPHERE-VEHICLE
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/vehicle/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=RewritePath=/vehicle/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[10].id=driver-docs
spring.cloud.gateway.server.webmvc.routes[10].uri=lb://ROUTESPHERE-DRIVER
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/driver/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[10].filters[0]=RewritePath=/driver/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[11].id=shipment-docs
spring.cloud.gateway.server.webmvc.routes[11].uri=lb://ROUTESPHERE-SHIPMENT
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/shipment/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[11].filters[0]=RewritePath=/shipment/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[12].id=invoice-docs
spring.cloud.gateway.server.webmvc.routes[12].uri=lb://ROUTESPHERE-INVOICE
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/invoice/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[12].filters[0]=RewritePath=/invoice/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[13].id=customer-docs
spring.cloud.gateway.server.webmvc.routes[13].uri=lb://ROUTESPHERE-CUSTOMER
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/customer/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[13].filters[0]=RewritePath=/customer/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[14].id=maintenance-docs
spring.cloud.gateway.server.webmvc.routes[14].uri=lb://ROUTESPHERE-MAINTENANCE
spring.cloud.gateway.server.webmvc.routes[14].predicates[0]=Path=/maintenance/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[14].filters[0]=RewritePath=/maintenance/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[15].id=trip-docs
spring.cloud.gateway.server.webmvc.routes[15].uri=lb://ROUTESPHERE-TRIP
spring.cloud.gateway.server.webmvc.routes[15].predicates[0]=Path=/trip/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[15].filters[0]=RewritePath=/trip/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[16].id=auth-docs
spring.cloud.gateway.server.webmvc.routes[16].uri=lb://ROUTESPHERE-AUTH
spring.cloud.gateway.server.webmvc.routes[16].predicates[0]=Path=/auth/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[16].filters[0]=RewritePath=/auth/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webmvc.routes[17].id=fuellog-docs
spring.cloud.gateway.server.webmvc.routes[17].uri=lb://ROUTESPHERE-FUELLOG
spring.cloud.gateway.server.webmvc.routes[17].predicates[0]=Path=/log/v3/api-docs
spring.cloud.gateway.server.webmvc.routes[17].filters[0]=RewritePath=/log/v3/api-docs,/v3/api-docs

server.forward-headers-strategy=framework